run :
	javac -cp ../commons-lang3-3.9/commons-lang3-3.9.jar main_dikjstra.java Matrice.java tbl_dikjstra.java
	java -cp ../commons-lang3-3.9/commons-lang3-3.9.jar:. main_dikjstra Matrice tbl_dikjstra

clean :
	rm -f *.class